### ISSUE TITLE
Logische IDs in eAbgabedaten

### ISSUE THREAD

**Issue by SAMMRE** [DAV-ABDA/eRezept-Beispiele#1]
Hallo zusammen,

vorab vielen Dank für das Bereitstellen der sehr hilfreichen Beispiele!

Ich habe einige Fragen bezüglich der Vergabe von logischen IDs der Ressourcen im Abgabedatenbundle. Die IDs werden verwendet, um innerhalb des Bundles auf die einzelnen Ressourcen referenzieren zu können. Da das Bundle nach meinem Verständnis allerdings lokal erzeugt wird und keine Kommunikation mit einem FHIR-Server vorausgesetzt wird, auf dem diese Ressourcen angelegt und mit einer ID versehen werden, ist mir aktuell noch unklar, ob es spezifische Anforderungen bezüglich der ID-Vergabe gibt.

Ist es korrekt, dass die logischen IDs der Einträge als UUIDs beim Erzeugen des Bundles vom erstellenden System generiert werden? Dabei beziehe ich mich auf die FHIR Dokumentation zu logical IDs und Referenzierungen innerhalb von Bundles:

https://www.hl7.org/fhir/resource.html#id

https://www.hl7.org/fhir/bundle.html#references

Ist es in diesem Fall ausreichend, wenn die IDs innerhalb des Bundles eindeutig sind, oder sollten sie - auch wenn die Wahrscheinlichkeit eine UUID doppelt zu erzeugen sehr gering ist - dokumentenübergreifend eindeutig sein?

Vielen Dank und vielen Grüße

SAMMRE

**Comment by ABDA-FHIR** [comment]
Hallo SAMMRE,

ja, die UUIDs werden lokal erzeugt. Da Sie ohnehin nur innerhalb des lokalen Systems prüfen könnten, ob die ID schon einmal vergeben wurde, wäre die Prüfung nie vollständig. Hier verlassen wir uns auf die prinzipiell Funktionsweise von UUID, zumal es inhaltlich ja weitere, eindeutige Unterscheidungsmerkmale gibt.

Bitte entschuldigen SIe auch die lange Antwortzeit. Wir werden zukünftig schneller antworten.

Viele Grüße
Das ABDA/DAV FHIR-Team

**Comment by SAMMRE** [comment]
Hallo ABDA/DAV FHIR-Team,

vielen Dank für die Klarstellung und Erläuterung!

Viele Grüße
SAMMRE
