### ISSUE TITLE
Wirkstoffverordnungen: ZusatzattributWirkstoffverordnung nur bei ARMIN?

### ISSUE THREAD

**Issue by thomasvoigt** [DAV-ABDA/eRezept-Beispiele#10]
Hallo zusammen,

die Wirkstoffverordnungen hier (z.B. [Wirkstoff-Verordnung V1](https://github.com/DAV-ABDA/eRezept-Beispiele/blob/main/Wirkstoff-Verordnung/Wirkstoff-Verordnung_V1/WS_V1_VerordnungArzt.xml)) haben in den [Abgabedaten](https://github.com/DAV-ABDA/eRezept-Beispiele/blob/main/Wirkstoff-Verordnung/Wirkstoff-Verordnung_V1/WS_V1_eAbgabedaten.xml#L215) das `ZusatzattributWirkstoffverordnung` gesetzt.

Im Konnektathon wurden meine Wirkstoffverordnungen mit gesetztem `ZusatzattributWirkstoffverordnung` vom ARZ Noventi abgelehnt mit der Begründung:
> Das Zusatzattribut "Wirkstoffverordnung" soll nur dann gesetzt werden, wenn es sich um eine ARMIN-Wirkstoff-Verordnung handelt.
Das ist ein spezieller Vertrag zwischen AOK-Plus und Apotheken in bestimmten Bundesländern.

Im Beispiel [Wirkstoff-Verordnung V1](https://github.com/DAV-ABDA/eRezept-Beispiele/blob/main/Wirkstoff-Verordnung/Wirkstoff-Verordnung_V1/WS_V1_VerordnungArzt.xml) kommt der Patient aus Köln, die Apotheke aus Hessen, die Krankenkasse ist die TK. Das passt nicht zur ARMIN-Modellregion Sachsen-Thüringen und der AOK Plus...

Welche Verwendung des `ZusatzattributWirkstoffverordnung` ist korrekt?
* `ZusatzattributWirkstoffverordnung` wird immer 1:1 durchgereicht von der Verordnung (wie hier in den Beispielen) _oder_
* `ZusatzattributWirkstoffverordnung`  ist nur relevant für ARMIN (wie von Noventi bei der Abrechnung durchgesetzt)

Vielen Dank und beste Grüße,
Thomas Voigt

**Comment by bneidhold** [comment]
ja es ist ein Bug in den Beispielen hier, ABER -> Das Problem dahinter bitte als JIRA Ticket bei der Gematik öffnen. 
Mein Beitrag: 
Im Simplifierprofil steht im Kleingedruckten (https://simplifier.net/packages/de.abda.erezeptabgabedatenbasis/1.1.0/files/427496):
Definition -> Ausprägung: ja Die Anwendung des Zusatzattributes ist nur gestattet, wenn dies in ergänzenden Verträgen (z.B. nach §§ 129 Absatz 5, 63, 64a, 140a SGB V) zwischen Krankenkassen und Apotheken bzw. deren Verbänden entsprechend geregelt ist.

- Da dieses Attribut ausschließlich in der Warenwirtschaft gesetzt werden kann und nicht durch das RZ muss ein RZ dies immer 1:1 durchleiten und darf es nicht verändern.
- Das einzig bekannte Projekt nach der Definition ist ARMIN und für ARMIN sind keine E-Rezepte definiert (weil die WG14Nr auch nicht Teil der E-Rezept-Spezifikation ist)

Daraus folgt für mich, dass dieses Attribut derzeit NIE gesetzt sein kann (also maximal für die Zukunft irgendwann mal relevant wird) und die Namensgebung des Attributes maximal unglücklich ist, weil Wirkstoffverordnung bei E-Rezept (im Gegensatz zu Papierrezepten) FirstClass strukturiert für alle verfügbar ist und nicht nur in Modellprojekten.

**Comment by thomasvoigt** [comment]
Vielen Dank für die Klarstellung! All das widerspricht dem erklärten Ziel, beim E-Rezept eine fehlerärmere Abrechnung zu ermöglichen. Ich habe meine Bedenken auch gegenüber der Gematik geäußert. 

Beste Grüße,
Thomas Voigt

**Comment by ABDA-FHIR** [comment]
Das Zuattribut 7 (Wirkstoffverordnung) wird in allen Beispielen entfert und damit die fehlerhafte Angabe in den Beispielen behoben. In der TA7 wird ein Hinweis zur Anwednung des Zusatzattributes ergänzt.

Inhaltliche Bewertung:
- Die Apotheke entscheidet über die Anwendung des Zusatzattributs, das ARZ kann eine Prüfung vornehmen und der Apotheke ggf. einen Hinweis zur richtigen Anwendung geben.  Eine abschließende Ablehnung durch das ARZ ist nicht zulässig.

- ARMIN-Wirkstoff-E-Verordnungen sind als Freitext-E-Verordnungen möglich und können auftreten. In diesen Fällen ist Zusatzattribut 7 anzuwenden.

- Perspektivisch kann das Zusatzattribut 7 bei E-Rezepten auf Grundlage weiterer ergänzender Verträge zwischen Krankenkassen und Apotheken bzw. deren Verbänden zur Anwendung kommen.

Viele Grüße
Das ABDA/DAV FHIR-Team
