### ISSUE TITLE
PZN-Verordnung_Impfstoff_V1 & PZN-Verordnung_Künstliche_Befruchtung fehlerhaft

### ISSUE THREAD

**Issue by scanacs-mrableski** [DAV-ABDA/eRezept-Beispiele#13]
Hallo in die Runde.
Ich würde gern einmal 2 fachliche Fehler aus den Beispieldaten melden.

#### PZN-Verordnung_Impfstoff_V1
Verordnung: 10259495 FSME Immun
Abgabe: 16938263 Gonal Fertigspritze.
Die Verordnungs-PZN ist ein Impfstoff. Die Abgabe-PZN ist ein Präparat zur künstlichen Befruchtung und nicht mit der verordneten PZN austauschbar.
Als Abgabe-PZN kommen FSME Immun - Präparate als Original oder Import infrage (z.B. PZN 11011981, 747182, 1123354, 10259495).

#### PZN-Verordnung_Künstliche_Befruchtung
In den Beispielszenarien wird eine Person mit einem Alter von 51 Jahren verwendet.
Geeignet wäre hier eine Alterswahl, die den Kriterien nach § 27a SGB V entspricht (weiblich <40 Jahre, männlich <50 Jahre), um ein plausibles Rezept zu simulieren und Fehlermeldungen aus Prüfungen zu vermeiden.

Es wäre schön wenn Sie ihre Beispieldaten dahingehend einmal prüfen und korrigieren könnten.

Viele Grüße
Marcel Rableski

**Comment by ABDA-FHIR** [comment]
Hallo,

vielen Dank für Ihre Hinweise.
Das Beispiel "PZN-Verordnung_Impfstoff_V1" wurde falsch übernommen und im Beispiel "PZN-Verordnung_Künstliche_Befruchtung" wird das Alter der Person angepasst.

Viele Grüße
Das ABDA/DAV FHIR-Team
