### ISSUE TITLE
DAV_EX_ERP_KostenVersicherter: Kategorie nur in TA7 definiert, aber nicht in FHIR?

### ISSUE THREAD

**Issue by DarthGizka** [DAV-ABDA/eRezept-Beispiele#17]
Die Erweiterung [DAV_EX_ERP_KostenVersicherter](https://simplifier.net/eRezeptAbgabedatenBasis/DAV_EX_ERP_KostenVersicherter/~overview) enthält die Kategorie des Betrages als CodeableConcept, aber ich sehe weder Einschränkungen für `coding.system` und `coding.code` noch eine Erklärung, welche Werte zulässig sind und was sie bedeuten sollen. 

Die einzige diesbezügliche Spezifikation, die ich finden konnte, ist etwas Freitext in einer Tabellenzelle auf Seite 29 in [TA7/002](https://gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/apotheken/technische_anlagen_aktuell/TA7_002_20220530.pdf). Habe ich da etwas übersehen?

An und für sich verbinde ich gerne bestimmte Elemente meiner Implementierung mit den entsprechenden Teilen der maschinenlesbaren Spezifikationen (Profile, ValueSets etc. pp.), damit die notwendigen Testfälle automatisch generiert werden können und nicht von fehleranfälligen Menschen (e.g. von mir) durch vollständiges Draufschauen auf Freitextdefinitionen manuell erstellt werden müssen. Analog dazu würde maschinenlesbare Spezifikation es erlauben, Beispielsammlungen wie die hier vorliegende automatisch auf vollständige Abdeckung solcher Spezifikationselemente prüfen zu lassen.

Anmerkung: DAV_EX_ERP_KostenVersicherter hat bezüglich der Prüfung ein höheres Gewicht als viele andere Spezifikationselemente, weil Eigenbeteiligung und von der Kasse übernommene Mehrkosten in FHIR und EDIFACT grundsätzlich anders behandelt werden und beim Übergang von FHIR zu EDIFACT zur Veränderung des ausgewiesenen Bruttobetrages führen (siehe 'Beispielrechnungen zu EFP-04' auf der letzten Seite von [Anhang 1 v003 zur TA7](https://gkv-datenaustausch.de/media/dokumente/leistungserbringer_1/apotheken/technische_anlagen_aktuell/TA7_Anhang1_003_20220519_Mapping.pdf).

**Comment by ABDA-FHIR** [comment]
Im Profile "DAV_PR_ERP_Abrechnungszeilen" (https://simplifier.net/erezeptabgabedaten/dav_pr_erp_abrechnungszeilen) wird durch das Element Invoice.lineItem.priceComponent.extension:KostenVersicherter (Kardinalität 1:3) die Kategorie (extension:Kategorie) und der Kostenbetrag (extension:Kostenbetrag) pro Abrechnungszeile angegeben. Die Angabe der Kategorie erfolgt über ein [CodeableConcept] welches mit einem Bindung (dav-vs-erp-kostenversicherterkategorie) versehen ist.

Viele Grüße
Das ABDA/DAV FHIR-Team
