### ISSUE TITLE
"Unit of Measure" {tbl} in <Medication>

### ISSUE THREAD

**Issue by thomasvoigt** [DAV-ABDA/eRezept-Beispiele#2]
Hallo zusammen,

in den E-Rezept-Beispielen wird bei der verordneten bzw. abgegebenen Menge oft `{tbl}` verwendet. Jedoch ist dieser Wert nicht im ValueSet für Mengenangaben enthalten: https://www.hl7.org/fhir/valueset-ucum-units.html

Wie ist hier zu verfahren? Gibt es ein anderes/erweitertes ValueSet?

Vielen Dank und beste Grüße,
Thomas

**Comment by murnic** [comment]
Wir hatten die Beispiele entsprechend angepasst und eine für den Patienten lesbare Angabe verwendet (z.B.: Tabletten oder St).
Das Feld Medication.amount.numerator.unit der KBV_PR_ERP_Medication_[...] ist als string definiert.
Die Angabe der Felder Medication.amount.numerator.system bzw. code sind optional und wurden in den Beispielen nicht verwendet.
