### ISSUE TITLE
Schlüsselwerte für DAV_CS_ERP_ZusatzattributFAMSchluesselMarkt

### ISSUE THREAD

**Issue by thomasvoigt** [DAV-ABDA/eRezept-Beispiele#20]
Hallo zusammen,

ich bin auf der Suche nach einer Dokumentation zur Verwendung der Werte für [DAV_CS_ERP_ZusatzattributFAMSchluesselMarkt](https://simplifier.net/erezeptabgabedatenbasis/dav-cs-erp-zusatzattributfamschluesselmarkt). In der Praxis erlebe ich immer wieder Überraschungen bei der Abrechnung, die ich bisher nur mit Versuch- und Irrtum gegenüber dem ARZ beheben konnte.

* Bisher war "Markt" eine statische Eigenschaft des Artikels (Codes 1,2,3). Falls der Markt sich jemals ändert, kann es sinnvoll sein, die Information für die Abrechnung zu persistieren, okay.
* Mit der Teilung der FHIR-Projekte in Basis/GKV/PKV kamen weitere Werte hinzu, die nichts mit dem Artikel selbst zu tun haben ("aut idem"), sich aber problemlos aus der vorliegenden Verordnung ermitteln lassen und sich auch später nicht ändern. Warum hat ein aut-idem-verordneter Artikel nun keinen Markt mehr? Warum wird "aut idem" noch einmal in der Abrechnung peristiert?
* Wann wird der Schlüssel 0 “nicht betroffen” gewählt?
* Wie ist die Präzedenz, wenn ein Artikel auf der Substitutionsausschlussliste “aut idem” verordnet wird?
* Für OTC-Verordnungen scheint die Markteinordnung subtil anders zu funktionieren (wie? warum?)

Für das Attribut DAV_CS_ERP_ZusatzattributFAMSchluesselMarkt wünsche ich mir eine erschöpfende Dokumentation, die nicht nur auf §129 SGB V verweist (so wie meine [Anfrage](https://service.gematik.de/browse/ERPFIND-201) im Service Desk der Gematik). 
* Aus der täglichen Praxis in der Apotheke lassen sich die Werte nicht herleiten, da sie bisher nicht für die Abrechnung relevant waren (das AVS zeigt sie nicht an, weil sie nicht notwendig sind). 
* In der TA7 und auch in der Anlage zum Mapping finden sich keine Hinweise, woher die Werte für das Attribut kommen (z.B. welche Kombination von PAC_APO-Attributen zu welchem Markt führt, aber insbesondere zu den neuen Codes 0,4,5). 
* In der Doku zum FHIR-Projekt tauchen die neuen Werte noch nicht auf. 
* ABDA/Avoxa sahen sich bereits zu mehreren Rundschreiben genötigt, um Teilaspekte zu erklären.

Wo finde ich diese Dokumentation?

Vielen Dank und beste Grüße,
Thomas Voigt

**Comment by ABDA-FHIR** [comment]
Sind die Fragen mit dem "Leitfaden zu den Zusatzattributen" in der TA7 (Kap. 8.2.2) beantwortet?
