### ISSUE TITLE
eAbgabedaten 1.3 - Abgabeinformationen - Substitution, Kardinalitäten der Rezeptänderungen

### ISSUE THREAD

**Issue by Tayling0184** [DAV-ABDA/eRezept-Beispiele#24]
Hallo in die Runde,

vermutlich ist die Frage allzu banal, dennoch würde ich diese gerne einmal loswerden: 

Wenn auf einem elektronischem Rezept eine PZN Verordnung vorliegt, und aufgrund der Rabattvertragserfüllung nicht die verordnete PZN, sondern eine dem RBV entsprechende PZN abgegeben wird, wird dann im eAbgabedatensatz in den Abgabeinformationen im Element "Substitution" das Kennzeichen "wasSubstituted" gesetzt?.

Dies ist nicht der Fall, oder? 
Das Kennzeichen "wasSubstituted" würde nur dann gesetzt werden, wenn dies aufgrund einer Rezeptänderung erfolgt, korrekt?
![image](https://user-images.githubusercontent.com/12819979/236275814-e1a871ae-e567-42f3-bee4-be387ff1d1b1.png)
Andernfalls würde die im Simplifierprofil abgebildete Kardinalität "0...*" sein?.

**Comment by ABDA-FHIR** [comment]
Hallo,

Richtig - nach Einhaltung der Abgaberangfolge nach Rahmenvertrag §129 SGB 5.
Bitte beachten Sie auch den Leitfaden zu den Zusatzattributen (TA7 Kap. 8.2.2).

Das Kennzeichen "wasSubstituted" wird immer (Fixed Value) im Kontext einer Rezeptänderung (Anpassung bzw. Korrektur der Verordnung) durch den Block "substitution" (Dokumentation der Rezeptänderung) gesetzt.
