### ISSUE TITLE
Abgabe von mehreren Medikamenten bei Nichtvorhanden des Verordneten

### ISSUE THREAD

**Issue by Kuehter** [DAV-ABDA/eRezept-Beispiele#25]
In den gesamten Beispielfällen wird leider kein Fall behandelt, der eine Abgabe von zwei Medikamenten berücksichtigt in den Grunddaten.
Dies kommt im Praxisfall selten vor, ist jedoch relevant.

**Comment by ABDA-FHIR** [comment]
Ein mögliches Beispiel einer Stückelung wurde in den PKV-Beispielen (https://github.com/DAV-ABDA/eRezept-Beispiele/tree/main/PKV/Wirkstoff-Verordnung) dargestellt. Bitte verstehen Sie, dass wir nicht proaktiv alle denkbaren Konstellationen abbilden können. Uns jedoch über Unterstützung bei der Erstellung relevanter Beispiele (z.B. dutch Pull Requests) freuen. Diesbezüglich haben wir einen Leitfaden (https://github.com/DAV-ABDA/eRezept-Beispiele/blob/2023-07-01/README_LEITFADEN.md) erstellt.
Bitte beachten Sie auch die Beispiele der gematik: https://github.com/gematik/eRezept-Examples.
