### ISSUE TITLE
ZusatzdatenEinheit-LineItem, Angabe der Charge bei parenteralen Rezepturen

### ISSUE THREAD

**Issue by Tayling0184** [DAV-ABDA/eRezept-Beispiele#26]
Liebes DAV Team, 

EDIT: Frage hat sich erledigt: In der TA1 V38 ist die Chargenangabe explizit nicht erwähnt als Bestandteil der zu übermittelnden Daten. Lesen Bildet.

Ich bräuchte bitte einmal Unterstützung hinsichtlich der Angabe der Charge bei Bestandteilen von parenteralen Rezepturen:
![image](https://github.com/DAV-ABDA/eRezept-Beispiele/assets/12819979/7b62e2dc-0da1-46bf-98fc-e0b89355547f)

Extension zur Angabe der Chargenbezeichnung. Angabe der Chargenbezeichnung bei authentifizierungspflichtigen Arzneimitteln (§ 10 Absatz 1c AMG), sofern auf der äußeren Umhüllung das Sicherheitsmerkmal (Data Matrix Code) vorhanden ist. 
Es soll die verwendete Charge von SecPha pflichtigen Ausgangsstoffen angegeben werden, korrekt? 

Das führt doch implizit dazu, dass die verwendeten Promille nicht mehr nur nach PZN aggregiert werden, ist das so gewünscht? (Das weicht ja glaube ich von den PRezeptdaten des FiveRx Standards aktuell ab, oder?)

Beispiel: Ich benötige für die Herstellung einer parenteralen Rezeptur 180mg Wirkstoff X.  Hierzu verwende ich 2 Fläschchen a 100mg mit der PZN 123, einmal die komplette Flasche 100mg(1000 Promille) mit der Charge A, und einmal 80mg (800 Promille) mit der Charge B. 

Auf dem Papierrezept hätte man aktuell die Angaben: 
PZN: 123
Faktor: 1800
FaktorKz: xx
Preis: xxx,xx
PreisKz: xx

usw. . auf dem eRezept hätte ich, sofern der Ausgangsstoff Securpharmpflichtig ist, zwei Elemente:

PZN: 123
Charge: A
Faktor: 1000
....

und:
PZN: 123
Charge: B
Faktor: 800
...

oder liege ich hier komplett neben der Spur? Wäre das weglassen der Charge ein Retaxgrund?

**Comment by ABDA-FHIR** [comment]
Angabe der Charge - technisch betrachtet - sicher auch in anderen Konstellationen denkbar:

Die Extension der Chargenbezeichnung kann mit Ihrer Kardinalität mehrfach angegeben werden.
![grafik](https://github.com/DAV-ABDA/eRezept-Beispiele/assets/80099385/a460b348-984b-4620-993b-965f6deb09e1)
Instanze-Bsp:

                <lineItem>
                    <extension url="http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Chargenbezeichnung">
                        <valueString value="Charge-A"/>
                    </extension>
                    <extension url="http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Chargenbezeichnung">
                        <valueString value="Charge-B"/>
                    </extension>
                    <sequence value="1"/>

**Comment by ABDA-FHIR** [comment]
Liebe(r) Tayling0184,

da hier vertragsrechtlichen Fragen und Einschätzungen gefordert sind, bitten wir um Verständnis, 
dass wir an dieser Stelle keine Aussagen treffen können.
Sie können aber gerne unter fhir(at)abda.de direkt mit uns in Kontakt treten.

Ihr ABDA/DAV FHIR-Team.
