### ISSUE TITLE
PKV Datamatix Code

### ISSUE THREAD

**Issue by UnixNetworks** [DAV-ABDA/eRezept-Beispiele#27]
Ist es korrekt das in Ihren Beispielen die Gebühren nicht in Cent angegeben sind?
Dies ist meines Erachtens lt. Spezifikation erforderlich.

**Comment by ABDA-FHIR** [comment]
Vielen Dank für den Hinweis - wir werden die Beispiele danach prüfen und anpassen.

**Comment by ABDA-FHIR** [comment]
Die Beispiele konnten nun angepasst werden.
