### ISSUE TITLE
PKV - PZN Verordnung Nr 8

### ISSUE THREAD

**Issue by UnixNetworks** [DAV-ABDA/eRezept-Beispiele#28]
Ist die Struktur in Ihrem PCode so korrekt?

{
    "A16": "50.97",
    "A17": [
        {
            "A10": "100",
            "A11": "42.83",
            "A9": "17543785"
        }
    ],
    "V1": "200.108.757.032.088.60",
    "V24": "17543779",
    "V25": "Efluelda Injek.susp. 2022/2023 1 FER o. KanÃ¼le N1",
    "V26": "1"
}

Meiner Meinung nach währe doch eher 

    "A17": [
        {
            "A9": "02567053",
            "A10": "1",
            "A11": "5097"
        }
    ],
    "A21": [
        {
            "A18": "17543785",
            "A19": "100",
            "A20": "4283"
        }
    ],

korrekt.

In der Spezifikation wird hier nicht näher auf die Struktur des PCodes im Falle einer Auseinzelung eingegangen.

**Comment by ABDA-FHIR** [comment]
Vielen Dank für den Hinweis - wir werden die Beispiele danach prüfen und anpassen.

**Comment by ABDA-FHIR** [comment]
Das Beispiel konnte nun angepasst werden.
