### ISSUE TITLE
Ungültiges Institutionskennzeichen (IKNR): Das übergebene Institutionskennzeichen im Versicherungsstatus entspricht nicht den Prüfziffer-Validierungsregeln

### ISSUE THREAD

**Issue by ManuelB** [DAV-ABDA/eRezept-Beispiele#31]
Wenn man versucht die Verordnungen von Paoli Privati in der RU mit flowtype und aktuellen Datum anzulegen, bekommt man folgende Fehlermeldung:

```
javax.ws.rs.WebApplicationException:
Error on https://erp-ref.zentral.erp.splitdns.ti-dienste.de
<?xml version=\"1.0\" encoding=\"utf-8\"?>
<OperationOutcome xmlns=\"http://hl7.org/fhir\">
  <meta>
    <profile value=\"http://hl7.org/fhir/StructureDefinition/OperationOutcome\"/>
  </meta>
  <issue>
    <severity value=\"error\"/>
      <code value=\"invalid\"/>
      <details>
        <text value=\"Ungültiges Institutionskennzeichen (IKNR): Das übergebene Institutionskennzeichen im Versicherungsstatus entspricht nicht den Prüfziffer-Validierungsregeln.\"/>
      </details>
   </issue>
</OperationOutcome>
```

Korrekt für die Allianz wäre laut folgender Liste:
168140346
https://github.com/PKV-Verband/PKV-IK-Liste/blob/main/ik_liste.csv#L2

**Comment by ManuelB** [comment]
Die Versichertennummer ist auch nicht korrekt:
Ungültige Versichertennummer (KVNR): Die übergebene Versichertennummer des Patienten entspricht nicht den Prüfziffer-Validierungsregeln.

**Comment by ManuelB** [comment]
Auch die Versichtennummer aus den KBV Beispielen erzeugt einen Fehler:
P123464113
javax.ws.rs.WebApplicationException: Error on https://erp-ref.zentral.erp.splitdns.ti-dienste.de <?xml version=\"1.0\" encoding=\"utf-8\"?>\n<OperationOutcome xmlns=\"http://hl7.org/fhir\"><meta><profile value=\"http://hl7.org/fhir/StructureDefinition/OperationOutcome\"/></meta><issue><severity value=\"error\"/><code value=\"invalid\"/><details><text value=\"Ung�ltige Versichertennummer (KVNR): Die �bergebene Versichertennummer des Patienten entspricht nicht den Pr�fziffer-Validierungsregeln.\"/></details></issue></OperationOutcome>

**Comment by ABDA-FHIR** [comment]
Die Beispiele haben nicht den Anspruch von Testdaten. Wir sind Ihren Anforderungen gefolgt und haben die IKs und KVNRs der Beispiele angepasst.
