### ISSUE TITLE
2025-01-15 Wirkstoff-Verordnung_V4 dosageInstruction

### ISSUE THREAD

**Issue by timorosenblatt** [DAV-ABDA/eRezept-Beispiele#36]
Die Auskommentierung der dosageInstruction hat kein Ende.

statt
```
<!--dosageInstruction>
    <text value="1-0-0-0"/>
  </dosageInstruction>
```

müsste es
```
<!--dosageInstruction>
    <text value="1-0-0-0"/>
  </dosageInstruction-->
```

lauten.

**Comment by ABDA-FHIR** [comment]
Vielen Dank, mit den weiteren Beispielen der MedicationDispenses wird nochmal eine gründliche Validierung stattfinden;-)
