### ISSUE TITLE
whenPrepared Definition: Die Angabe muss im Format JJJJMMTT:HHMM erfolgen. Beispiele nutzen YYYY-MM-DD

### ISSUE THREAD

**Issue by ManuelB** [DAV-ABDA/eRezept-Beispiele#6]
Hallo,
im DAVPRBaseZusatzdatenHerstellung Profile wird angegeben, dass whenPrepared im Format JJJJMMTT:HHMM angegeben muss:
https://simplifier.net/eRezeptAbgabedatenBasis/DAVPRBaseZusatzdatenHerstellung/~xml

![Bildschirmfoto von 2021-11-09 11-35-13](https://user-images.githubusercontent.com/457641/140908810-18369988-3ff6-493d-be52-b1780a7aac23.png)

In den Beispielen wird es aber im Format YYYY-MM-DD angegeben:
https://github.com/DAV-ABDA/eRezept-Beispiele/blob/main/PZN-Verordnung_Nr_1/PZN_Nr1_eAbgabedaten.xml#L120

Hier wird auch im Profile kein Constraint definiert. Dementsprechend werden wir uns an die Beispiele halten.

Schönen Gruß
    Manuel

**Comment by ABDA-FHIR** [comment]
Sehr geehrter Herr Blechschmidt,

in den abgeleiteten Profilen vom Typ MedicationDispense wird das Feld "whenPrepared" als Angabe folgender Daten genutzt:

DAV_PR_ERP_Abgabeinformationen.whenHandedOver -> Abgabedatum (YYYY-MM-DD)
--> ist in jedem Abgabedatensatz vorhanden

DAV_PR_ERP_ZusatzdatenHerstellung.whenHandedOver -> Herstellungsdatum und Zeitpunkt der Herstellung (JJJJMMTT:HHMM)
--> im Kontext von Herrstellungssegmenten (Rezepturen)

In den betreffenden Beispielen geben wir das Herstellungsdatum und den Zeitpunkt der Herstellung entsprechend an:
Rezeptur-Verordnung_Nr_1
Rezeptur-parenterale_Zytostatika

Viele Grüße
Das ABDA/DAV FHIR-Team

**Comment by ManuelB** [comment]
Tut mir leid, hier wäre das korrekte Beispiel:

https://github.com/DAV-ABDA/eRezept-Beispiele/blob/main/Rezeptur-Verordnung_Nr_1/Rez_Nr1_eAbgabedaten.xml#L239

Erwartet:
```
...
        <whenPrepared value="2021052700:00"/>
...
```

Wirklichkeit:
```
...
        <whenPrepared value="2021-05-27T00:00:00Z"/>
...
```

**Comment by ABDA-FHIR** [comment]
Die Vorgabe  (JJJJMMTT:HHMM) in der Beschreibung des Feldes werden wir überprüfen und entsprechend anpassen.

Laut FHIR-Spezifikation (https://www.hl7.org/fhir/datatypes.html#dateTime) ist die Angabe wie in den Beispielen, als ISO 8601 (UTC), zu nutzen.

Vielen Dank für Ihren Hinweis.

**Comment by ManuelB** [comment]
Dankteschön!
