### ISSUE TITLE
BVG Rezepte sind zuzahlungsbefreit

### ISSUE THREAD

**Issue by magrimuc** [DAV-ABDA/eRezept-Beispiele#7]
PZN-Verordnung_Nr_2 enthält ein Rezept, das nach BVG abgerechnet werden soll. (Nebenbei hat der Patient bei der KK den Status gebührenpflichtig.)
Nach dieser Quelle würde die Zuzahlung entfallen:

https://www.deutschesapothekenportal.de/rezept-retax/dap-lexikon/bundesversorgungsgesetz-bvg/

Es ist also zu klären: darf auf dem Rezept noch der Gebührenpflichtigkeitsstatus des Patienten bei KK stehen?
Ist es korrekt, dass BVG diesen Status überstimmen muss? (Aufgabe des AVS mglw?)
Ist die Abgabe zu korrigieren? IST: ZZ = 5€. SOLL: ZZ = 0

**Comment by thomasvoigt** [comment]
Gibt es hierzu schon eine Klarstellung/Berichtigung?

**Comment by murnic** [comment]
Das Beispiel (https://simplifier.net/eRezept/aea2f4c5-675a-4d76-ab9b-7994c80b64ec/~xml) wird momentan von der KBV geprüft.

**Comment by ABDA-FHIR** [comment]
Das Beispiel wurde von der KBV angepasst (von Zuzahlungspflicht befreit / gebührenfrei).

**Comment by scanacs-agruhn** [comment]
Leider ist der Zuzahlungsbetrag in den Abgabedaten immer noch nicht korrekt. Laut unserer Fachabteilung muss dieser folgendermaßen geändert werden:

![image](https://user-images.githubusercontent.com/53820628/185920686-a8fb3b61-2a92-41d9-bcac-7f9df8d77d3f.png)

**Comment by ABDA-FHIR** [comment]
Vielen lieben Dank für den Hinweis. Wir werden das Beispiel entsprechend anpassen:-)

**Comment by aWuttig** [comment]
Danke! Wann wird das passieren?
