### ISSUE TITLE
ZusatzdatenEinheit Zaehler not sequential numbers

### ISSUE THREAD

**Issue by mkarpusiewicz-am** [DAV-ABDA/eRezept-Beispiele#8]
Hey,

I've noticed in the example https://github.com/DAV-ABDA/eRezept-Beispiele/blob/main/Rezeptur-parenterale_Zytostatika/Rez_parenterale_Zytostatika_eAbgabedaten.xml that all 3 invoices of type ZusatzdatenEinheit have Zaehler set to 1:

```
<extension url="http://fhir.abda.de/eRezeptAbgabedaten/StructureDefinition/DAV-EX-ERP-Zaehler">
    <valuePositiveInt value="1" />
</extension>
```

Shouldn't they be sequential numbers 1,2,3 the same as for MedicationDispense entries in the same example?

Thanks!

**Comment by ABDA-FHIR** [comment]
Hallo,

the counter (DAV-EX-ERP-Zaehler) is used in the DAV-PR-ERP-ZusatzdatenHerstellung segments as well as in the DAV-PR-ERP-ZusatzdatenEinheit.
The DAV-PR-ERP-ZusatzdatenEinheit are each assigned to a DAV-PR-ERP-ZusatzdatenHerstellung and are counted separately.
Please view the StyleSheet of the exmaple -> Rez_parenterale_Zytostatika_eAbgabedaten.html

Kind regards,
the ABDA/DAV FHIR-Team

**Comment by mkarpusiewicz-am** [comment]
@ABDA-FHIR Thank you for an quick answer.
