### ISSUE TITLE
Wirkstoff-Verordnung\Wirkstoff-Verordnung_V3: Zusatzattribute fehlerhaft

### ISSUE THREAD

**Issue by thomasvoigt** [DAV-ABDA/eRezept-Beispiele#9]
Hi there!

Die Beschreibung für [Wirkstoff-Verordnung\Wirkstoff-Verordnung_V3](https://github.com/DAV-ABDA/eRezept-Beispiele/blob/main/Wirkstoff-Verordnung/Wirkstoff-Verordnung_V3/WS_V3_eAbgabedaten.xml) lautet:
> Merkmal Abgabedaten: Abweichung vom Rabattvertrag (Nicht-Verfügbarkeit + Freitext), keine Abgabe eines preisgünstigen FAM (dringender Fall)

Die abgegebene PZN 00761360 ist ein Generikum und gehört in die Gruppe "PreisgünstigeFAM".

Tatsächlich sind die Abgaberangfolgen der Zusatzattribute so belegt:
* Rabattvertragserfuellung: 2 (nein, nicht verfügbar) mit textueller Begründung --> OK
* PreisguenstigesFAM: 0 (nicht relevant) --> lt. Beschreibung erwarte ich hier 3 (nein, dringender Fall)
* ImportFAM: 0 (nicht relevant) --> da ein Artikel abgegeben wurde, erwarte ich ihn in dieser Gruppe mit 1 (ja, abgegeben)

Die IKNR der abgebenden Apotheke ist leider noch immer ungültig (Prüfsumme).

Fragen dazu:
* Wie ist die korrekte Belegung der Zusatzattribute?
* Bei Wirkstoffverordnungen darf meines Wissens nach neben dem Rabattartikel nur ein Artikel aus dem generischen Markt abgegeben werden. Das Rezept wäre daher gar nicht erfüllbar, wenn gegen die preisgünstigen Artikel ein "dringender Fall" spricht?
* Nach meinem Verständnis schließen sich die Gruppen "PreisguenstigesFAM" und "ImportFAM" aus. Gibt es tatsächlich Situationen, in denen zwei Begründungen abgegeben werden können? 

Vielen Dank und beste Grüße,
Thomas Voigt

**Comment by murnic** [comment]
Hallo Herr Voigt,

vielen Dank für die Fehlerbeschreibung. 
In der Tat ist das Zusatzattribut 3 - PreisguenstigesFAM mit 3 zu füllen (fehlerhafte Übernahme aus meiner fachlichen Vorlage:-(
Beim Zusatzattribut 4 - ImportFAM habe ich die Notiz: "es gibt kein Import"

Zum Thema der IKNR bin ich mir nicht sicher ob ich eine gültige aber dennoch nicht vergebene Beispiel IKNR für die Darstellung finde - prüfe den Wunsch aber weiter.

Ihre Fragen nehme ich nochmal mit und stimme sie weiter ab.

Mfg, 
Nico Murawski

**Comment by thomasvoigt** [comment]
Hallo Herr Murawski,

das Beispiel funktioniert so noch immer nicht.

* Wenn `Rabattvertragserfuellung` nicht abgegeben wird (2, "nein, nicht verfügbar") und `PreisguenstigeFAM` nicht abgegeben wird (3, "nein, dringender Grund"), dann kann die Wirkstoffverordnungen meines Wissens nach nicht erfüllt werden und die Verordnung muss zurückgegeben werden. Ein Durchfallen auf `ImportFAM` ist nicht erlaubt, wie Ihre Notiz auch andeutet.
* Die abgegebene PZN 00761360 ist ein Generikum und gehört in die Gruppe `PreisguenstigeFAM`. Das widerspricht der Angabe, dass wegen pharmazeutischer Bedenken/dringender Gründe eben *kein* FAM dieser Gruppe abgegeben wurde.

Nach unserem Verständnis der Rahmenverträge entfällt stets eine der beiden Gruppen `PreisguenstigeFAM` oder `ImportFAM`. Umso verwirrter sind wir nun durch dieses Beispiel, das in seiner textuellen Bescrheibung impliziert, dass alle drei Gruppen zur Auswahl stünden (und das sogar bei einer Wirkstoffverordnung).

Lässt sich von Seiten der KBV/DAV/ABDA bitte klären, ob es überhaupt einen Fall geben kann, bei dem alle drei Gruppen zur Wahl stehen? Bei dem die dritte "Abgaberangfolge" nicht automatisch "nicht zutreffend" ist?

Vielen Dank und beste Grüße,
Thomas Voigt

**Comment by magrimuc** [comment]
Hallo Herr Voigt,
 folgende Berichtigungen möchte ich anmerken:

1. pkt1: Wenn ...
richtig ist: doch. Nach TA7 Anlage 1 befinden wir uns in Markt 1 (Generika), Rabattvertragserfüllung Nein, (Nicht-Verfügbarkeit) und Preisgünstig Nein (dringender Fall). Das war auf dem Papierrezept das Sonderkennz. 6 und das gibt es im eRezept in exakt der Kombination. 
ImportFAM trifft für Generika nicht zu. Korrekt.

2. pkt2: PreisguenstigeFAM. 
Die abgegebene (z.B. weil vorrätige) PZN kostet 14,08€. Die preisgünstigsten 4 sind für 13,40€ (und billiger) zu haben. Damit ist das Ramipril 00761360 kein preisguenstiges FAM. (Durch Begründung "dringender Fall" trotzdem abgebbar.)

**Comment by thomasvoigt** [comment]
Hallo Herr Grillo,

herzlichen Dank für den Verweis auf die Mapping-Regeln in TA7 Anhang 1! Die Tabelle auf S. 71f beschreibt die möglichen Fälle sehr ausführlich. Der Knoten in meinem Hirn hat sich damit gelöst (Abgaberangfolge "nein, ..." heißt mitnichten, dass aus dieser Gruppe nichts abgegeben wurde).

Ich schließe das Ticket, das Beispiel ist nach der Anpassung durch Herrn Murawski korrekt. Danke nochmal!

Beste Grüße,
Thomas Voigt
